# Copyright (C) 2026 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GCC; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>.

# G++ testsuite that uses the `dg.exp' driver.

# Load support procs.
load_lib g++-dg.exp

if {![istarget i*86-*-mingw*]
  && ![istarget x86_64-*-mingw*]} {
    return 0
}

# If a testcase doesn't have special options, use these.
global DEFAULT_CXXFLAGS
if ![info exists DEFAULT_CXXFLAGS] then {
    set DEFAULT_CXXFLAGS " -pedantic-errors -Wno-long-long"
}

# Initialize `dg'.
dg-init

# Main loop.
set comp_output [g++_target_compile \
    "$srcdir/$subdir/../trivial.C" "trivial.S" assembly \
    "additional_flags=-gcodeview"]
if { ! [string match "*: target system does not support the * debug format*" \
    $comp_output] } {
    remove-build-file "trivial.S"
    g++-dg-runtest [lsort [glob -nocomplain $srcdir/$subdir/*.C]] \
	    "" $DEFAULT_CXXFLAGS
}

# All done.
dg-finish
